skip_branch_with_pr: true
branches:
  only:
    - master

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install pytest"
  - "%PYTHON%\\python.exe setup.py --quiet clean develop"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest"
